[defaults]
platform = {{ platform }}
distro = icharlie
{% if toolchain_version %}
toolchain-version = {{ toolchain_version }}
{% endif %}

[monolith]
type = git
url = {{ monolith_url }}
revision = {{ monolith_revision }}
cmake-path-identifier = MONOLITH_DIR
action = lib

[project]
action = softfs
cmake-variables = MONOLITH_TOOLCHAIN_CI=ON
